# Exercise 1 

```{r libraries, message=FALSE}
library(tidyverse)
library(sf)
library(raster)
library(ggplot2)
```

## Tasks 1 - 3

```{r data, include=FALSE}
data_schwein <- read_delim("data/wildschwein_BE.csv", delim = ',')

ggplot(data = data_schwein) + geom_point(aes(x = Long, y = Lat, color = TierID))
```

As a next task, we convert our dataframe `data_schwein` into a spatial feature `sf` object.

```{r convert into Sf}
data_schwein_sf <- st_as_sf(data_schwein, coords = c("Long", "Lat"),
                            crs = 4326)
```

## Task 4: Project data from WGS84

```{r intoSwissCRS}
data_schwein_CH <- st_transform(data_schwein_sf, 2056)
```

```{r convex hull}
data_schwein_grouped <- data_schwein_CH %>%
  group_by(TierID) %>%
  summarise()

# Calculate now the convex hull
mcp <- st_convex_hull(data_schwein_grouped)
```

```{r plot mcp}
mcp_plot <- ggplot(data = mcp) +
  geom_sf(aes(fill = TierID),alpha = 0.5) + coord_sf(datum = 2056)
```

## Task 5: Import Raster Data

```{r import raster data}
pk100_BE <- brick("data/pk100_BE_2056.tif")
plot(pk100_BE)

# remove the 4th layer
pk100_BE <- subset(pk100_BE, 1:3)
plot(pk100_BE)
```


## Task 6: Adding a background map

```{r background map, echo=FALSE}
library(tmap)
 
tm_shape(pk100_BE) + 
  tm_rgb() +
  tm_shape(mcp) +
  tm_polygons(col = "TierID",alpha = 0.4,border.col = "red") +
  tm_legend(bg.color = "white")

```

